services:
  slskd-bot:
    image: ghcr.io/illegitimatehumans/slskd-message-bot:latest
    container_name: slskd-bot
    user: "${PUID}:${PGID}"
    cap_drop:
      - ALL
    environment:
      - TZ=${TZ}
      - SLSKD_URL=${SLSKD_URL}
      - SLSKD_API_KEY=${SLSKD_API_KEY}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./logs:/app/logs
      - ./message.txt.example:/app/message.txt.example:ro
    networks:
      - media-stack
networks:
  media-stack:
    external: true
